language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t floriankuc/docker-ci-react-template -f Dockerfile.dev .

script:
  - docker run -e CI=true floriankuc/docker-ci-react-template npm run test
